// Generated by CoffeeScript 1.3.1
(function() {
  var html, jQuery, jsdom;

  jsdom = require('jsdom/lib/jsdom').jsdom;

  jQuery = require('jquery');

  html = "<!DOCTYPE html>\n<html>\n  <head>\n  </head>\n  <body>\n    <div id='transparency'>\n    </div>\n  </body>\n</html>\"";

  global.document = jsdom(html);

  global.window = document.createWindow();

  global.jQuery = global.$  = jQuery.create(window);

  global.Transparency = require('../src/transparency');

}).call(this);
