// Generated by CoffeeScript 1.3.1
(function() {

  beforeEach(function() {
    return this.addMatchers({
      htmlToBeEqual: function(expected) {
        var actual, formatHtml;
        formatHtml = function(html) {
          return html.replace(/\s/g, '').toLowerCase();
        };
        actual = formatHtml(this.actual);
        expected = formatHtml(expected);
        this.message = function() {
          return actual + '\n\n' + expected;
        };
        return actual === expected;
      }
    });
  });

}).call(this);
