// Generated by CoffeeScript 1.3.1
(function() {

  if (typeof module !== "undefined" && module !== null ? module.exports : void 0) {
    global.document = require('jsdom/lib/jsdom').jsdom("<!DOCTYPE html>\n<html>\n  <head>\n  </head>\n  <body>\n  </body>\n</html>");
    global.window = document.createWindow();
    global.$ = global.jQuery = require('jquery').create(window);
  }

  beforeEach(function() {
    return this.addMatchers({
      htmlToBeEqual: function(expected) {
        var actual, formatHtml;
        formatHtml = function(html) {
          return html.replace(/\s/g, '').toLowerCase();
        };
        actual = formatHtml(this.actual);
        expected = formatHtml(expected);
        this.message = function() {
          return actual + '\n\n' + expected;
        };
        return actual === expected;
      }
    });
  });

}).call(this);
